# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K6DurationExtractor < Formula
  desc "Tool to extract the duration information per request from the K6 csv output."
  homepage "https://github.com/janritter/k6-duration-extractor"
  version "1.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.8/k6-duration-extractor_1.1.8_darwin_amd64.tar.gz"
      sha256 "558654d00308cc35e2e81c23ced4d893f20552eef259dc09d29279c37975c379"

      def install
        bin.install "k6-duration-extractor"
      end
    end
    on_arm do
      url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.8/k6-duration-extractor_1.1.8_darwin_arm64.tar.gz"
      sha256 "089a83b17c615c1fcf16b82b58b1ff7bafef44e82a63fb421baa831a159b627f"

      def install
        bin.install "k6-duration-extractor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.8/k6-duration-extractor_1.1.8_linux_amd64.tar.gz"
        sha256 "aa983e5548478c292695869cc094791c740e989bb667e3a577a6cb34961061af"

        def install
          bin.install "k6-duration-extractor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.8/k6-duration-extractor_1.1.8_linux_arm64.tar.gz"
        sha256 "7f462d19b3aa6d469b39852120e26f2c241d803b736b5308486d330bc4a96547"

        def install
          bin.install "k6-duration-extractor"
        end
      end
    end
  end
end
