# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K6DurationExtractor < Formula
  desc "Tool to extract the duration information per request from the K6 csv output."
  homepage "https://github.com/janritter/k6-duration-extractor"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.3/k6-duration-extractor_1.1.3_darwin_arm64.tar.gz"
      sha256 "578e85017a93baf1a0443784e23f35e7324913869f4d0239a376987dda3387fc"

      def install
        bin.install "k6-duration-extractor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.3/k6-duration-extractor_1.1.3_darwin_amd64.tar.gz"
      sha256 "9e926f79d9bc996e55ed01f12583aae2f35b5344e1227bb0861f816f1a14d474"

      def install
        bin.install "k6-duration-extractor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.3/k6-duration-extractor_1.1.3_linux_arm64.tar.gz"
      sha256 "c7c4b93752feda3a5af63547b5eab738613f8b353b774c4810252b2dd0013b15"

      def install
        bin.install "k6-duration-extractor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janritter/k6-duration-extractor/releases/download/1.1.3/k6-duration-extractor_1.1.3_linux_amd64.tar.gz"
      sha256 "d89065db0ac5f7b4a64c6e67cca5424f1a7b07de1e64c322776853652a201ccd"

      def install
        bin.install "k6-duration-extractor"
      end
    end
  end
end
